@hostName = https://dystancetest.azurewebsites.net

{{hostName}}/api//semesters/students/get?id=15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFlZDllOTZmLTk3NWUtNDRmYi05MjBmLTNjZGNmMzJiYzJiZiIsIm5iZiI6MTYwNjA1NzM1MCwiZXhwIjoxNjA2MTQzNzUwLCJpYXQiOjE2MDYwNTczNTB9.RAv8N9MYlqIom1p0jOgP3GXaf4SL1VcO9tnUL2E11zE
